version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/sentinel"
    schedule:
      interval: "yearly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/paused"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
# c2e-touch 6f1e8d3c
